"""Human-readable help text for scanner table columns."""


LTF_IGNITION_COLUMN_HELP = {
    "symbol": "Binance USDT-M perpetual contract symbol.",
    "ignition_state": "Current lower-timeframe state for the selected interval, such as Long ignition, Short ignition, Compression, Watch, or Neutral.",
    "ignition_tf": "The 5-minute, 15-minute, or 1-hour interval with this symbol's strongest current ignition score.",
    "ltf_ignition_score": "Overall 0-100 lower-timeframe ignition score. It blends recent compression, volatility expansion, volume, open interest, range breakout, and relative strength.",
    "conviction_net": "Continuous directional confirmation from -1 to +1. Positive favors a long setup, negative favors a short setup, and larger absolute values mean stronger confirmation.",
    "atr_percentile": "Current ATR ranked against its recent history. A low percentile suggests compressed volatility; a high percentile suggests an already active or expanded market.",
    "atr_roc": "Rate of change in ATR over the last three candles. Positive values mean volatility is expanding; negative values mean it is contracting.",
    "atr_compression_score": "0-100 score for how strongly recent price, volume, and open-interest behavior resembles a quiet compression phase.",
    "atr_expansion_score": "0-100 score for how strongly volatility is expanding now, especially after recent compression.",
    "volume_zscore": "How unusual the latest quote volume is versus recent history. For example, +2 means roughly two standard deviations above normal.",
    "oi_zscore": "How unusual the latest open-interest activity is versus recent history. A large positive value indicates an open-interest surge.",
    "taker_imbalance": "Aggressive buyer-versus-seller imbalance. Positive values indicate stronger market buying; negative values indicate stronger market selling.",
    "cvd_3bar_slope": "Three-candle slope of cumulative taker-volume delta. Positive means aggressive buying is accumulating; negative means aggressive selling is accumulating.",
    "basis_bp": "Perpetual price minus spot price, measured in basis points. Positive means the perpetual trades above spot; negative means it trades below spot.",
    "basis_delta_3bar_bp": "Change in the perpetual-versus-spot basis over three candles, in basis points. Positive means the premium is rising.",
    "price_distance_from_vwap_atr": "Price distance from rolling VWAP measured in ATR units. Positive is above VWAP; negative is below VWAP.",
    "breakout_distance_atr": "Distance beyond the prior range boundary measured in ATR units. Positive indicates an upside break; negative indicates a downside break.",
    "break_hold_confirmed": "Checked when price has closed beyond its prior range boundary for two consecutive candles.",
    "rs_vs_btc": "The symbol's return minus BTC's return over the relevant lookback. Positive means it outperformed BTC.",
    "rs_vs_eth": "The symbol's return minus ETH's return over the relevant lookback. Positive means it outperformed ETH.",
    "compression_recent_bars": "Number of recently compressed candles found inside this timeframe's compression lookback window.",
    "bars_since_trigger": "Candles elapsed since the latest new ignition trigger. Smaller values are fresher; 999 means no recent trigger was found.",
    "tf_alignment_score": "Number of the 5m, 15m, and 1h intervals pointing in the selected direction. Best Setup eligibility requires at least two.",
    "ignition_score_5m": "Current 0-100 ignition score calculated on the 5-minute interval.",
    "ignition_score_15m": "Current 0-100 ignition score calculated on the 15-minute interval.",
    "ignition_score_1h": "Current 0-100 ignition score calculated on the 1-hour interval.",
}


HTF_EXPANSION_COLUMN_HELP = {
    "symbol": "Binance USDT-M perpetual contract symbol.",
    "htf_expansion_direction": "Current higher-timeframe condition: confirmed Long/Short expansion, an unconfirmed watch, Compression, or Neutral.",
    "htf_expansion_score": "Overall 0-100 higher-timeframe expansion score after combining volatility, participation, structure, daily quality, persistence, and the BTC regime.",
    "htf_atr_percentile": "Current higher-timeframe ATR ranked against its recent history. Low values suggest compression; high values suggest elevated volatility.",
    "htf_atr_roc": "Rate of change in higher-timeframe ATR over the last three candles. Positive values mean volatility is expanding.",
    "htf_atr_compression_score": "0-100 score for how strongly higher-timeframe volatility and participation resemble a compression phase.",
    "htf_atr_expansion_score": "0-100 score for the current increase in higher-timeframe volatility.",
    "htf_breakout_distance_atr": "Price distance beyond the higher-timeframe range boundary, measured in ATR units. The sign indicates breakout direction.",
    "htf_range_width_atr": "Width of the recent higher-timeframe trading range measured in ATR units.",
    "daily_structure_score": "Stronger of the 0-100 daily long and short structure scores, based on breaks or rejections, EMA structure, volume, and OI persistence.",
    "daily_atr_percentile": "Current daily ATR ranked against recent daily history. Low values indicate quieter daily volatility; high values indicate greater expansion.",
    "daily_volume_ratio": "Latest daily quote volume divided by its preceding 20-day average. Above 1 means volume is running above that baseline.",
    "daily_volume_persistence_days": "Consecutive recent days whose quote volume remained above its rolling 20-day average.",
    "daily_oi_persistence_days": "Consecutive recent days with increasing open-interest value.",
    "daily_swing_high": "Most recent relevant daily pivot high, or the fallback high from the recent daily lookback.",
    "daily_swing_low": "Most recent relevant daily pivot low, or the fallback low from the recent daily lookback.",
    "daily_long_confirmed": "Checked when daily long quality is at least 55 and price has broken, reclaimed, or held above an important high.",
    "daily_short_confirmed": "Checked when daily short quality is at least 55 and price has broken below or rejected an important daily level.",
    "btc_daily_regime": "Bitcoin's daily backdrop: Bull trend, Range, Drawdown, or Unknown. It adjusts directional HTF expectations.",
    "btc_daily_regime_score": "0-100 Bitcoin daily trend score. At least 70 is Bull trend; 35 or below is Drawdown; values between are Range.",
    "htf_momentum_score": "0-100 higher-timeframe leadership score emphasizing 24-hour through 7-day strength, trend quality, participation, OI, and funding.",
    "htf_setup_score": "Higher-timeframe momentum score after penalizing overextension, helping distinguish strong opportunities from moves that may already be late.",
    "htf_relative_strength_score": "Percentile-ranked higher-timeframe performance relative to BTC across the 24-hour, 72-hour, and 7-day windows.",
    "volume_score": "0-100 volume participation score derived from current volume relative to its recent baseline and statistical norm.",
    "oi_score": "0-100 open-interest expansion score. Higher values indicate stronger confirmation from changing market exposure.",
    "rs_24h": "Raw 24-hour return minus BTC's 24-hour return. Positive means the symbol outperformed BTC.",
    "rs_72h": "Raw 72-hour return minus BTC's 72-hour return. Positive means the symbol outperformed BTC.",
}


BEST_SETUPS_COLUMN_HELP = {
    "symbol": "Binance USDT-M perpetual contract symbol.",
    "best_setup_state": "Combined classification after comparing the lower-timeframe direction with higher-timeframe and daily structure: Long best setup, Short best setup, Compression context, or Mixed setup.",
    "best_setup_score": "Final 0-100 combined score: 55% LTF ignition, 30% HTF expansion, and 15% directional alignment.",
    "ignition_state": "Current lower-timeframe condition for the selected interval, such as Long ignition, Short ignition, Watch, Compression, or Neutral.",
    "ignition_tf": "The 5-minute, 15-minute, or 1-hour interval with this symbol's strongest current ignition score.",
    "ltf_ignition_score": "0-100 lower-timeframe ignition score blending recent compression, volatility expansion, volume, open interest, range breakout, and relative strength.",
    "htf_expansion_direction": "Current higher-timeframe condition: confirmed Long/Short expansion, an unconfirmed watch, Compression, or Neutral.",
    "htf_expansion_score": "0-100 higher-timeframe expansion score combining volatility, participation, structure, daily quality, persistence, and the BTC regime.",
    "daily_structure_score": "Stronger of the 0-100 daily long and short structure scores, based on breaks or rejections, EMA structure, volume, and OI persistence.",
    "daily_volume_persistence_days": "Consecutive recent days whose quote volume remained above its rolling 20-day average.",
    "daily_oi_persistence_days": "Consecutive recent days with increasing open-interest value.",
    "btc_daily_regime": "Bitcoin's daily backdrop: Bull trend, Range, Drawdown, or Unknown. It adjusts directional HTF expectations.",
    "alignment_score": "Directional context used in the final score: 100 when LTF, HTF, and daily direction agree; 70 in HTF compression; otherwise 35.",
    "tf_alignment_score": "Number of the 5m, 15m, and 1h intervals pointing in the selected LTF direction. Best Setup eligibility requires at least two.",
    "bars_since_trigger": "Candles elapsed since the latest new ignition trigger. Smaller values are fresher; new Best Setups require no more than three.",
    "volume_zscore": "How unusual the latest quote volume is versus recent history. For example, +2 means roughly two standard deviations above normal.",
    "oi_zscore": "How unusual the latest open-interest activity is versus recent history. A large positive value indicates an open-interest surge.",
    "taker_imbalance": "Aggressive buyer-versus-seller imbalance. Positive values indicate stronger market buying; negative values indicate stronger market selling.",
    "cvd_3bar_slope": "Three-candle slope of cumulative taker-volume delta. Positive means aggressive buying is accumulating; negative means aggressive selling is accumulating.",
    "basis_bp": "Perpetual price minus spot price, measured in basis points. Positive means the perpetual trades above spot; negative means it trades below spot.",
    "basis_delta_3bar_bp": "Change in the perpetual-versus-spot basis over three candles, in basis points. Positive means the premium is rising.",
    "atr_percentile": "Current lower-timeframe ATR ranked against recent history. Low values suggest compression; high values indicate elevated volatility.",
    "atr_roc": "Rate of change in lower-timeframe ATR over the last three candles. Positive values mean volatility is expanding.",
    "breakout_distance_atr": "Distance beyond the prior lower-timeframe range boundary measured in ATR units. Positive indicates an upside break; negative indicates a downside break.",
    "rs_vs_btc": "The symbol's return minus BTC's return over the relevant LTF lookback. Positive means it outperformed BTC.",
    "rs_vs_eth": "The symbol's return minus ETH's return over the relevant LTF lookback. Positive means it outperformed ETH.",
}
